CREATE TABLE PROJECT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255)
);

CREATE TABLE CONTRACT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255),
	CODE VARCHAR(12),
	DESCRIPTION VARCHAR(2000),
	BUDGET INT(12),
	COMMITTED_COST INT(12),
	FORECAST INT(12),
	PAID INT(12),
	COMPLETED_PERCENTAGE INT(3),
	VENDOR VARCHAR(64),
	PROJECT_ID INT(12)
);

INSERT INTO PROJECT (NAME) VALUES('Home Building');
INSERT INTO PROJECT (NAME) VALUES('Bridge Building');

INSERT INTO CONTRACT (NAME, CODE, DESCRIPTION, BUDGET, COMMITTED_COST, FORECAST, PAID, COMPLETED_PERCENTAGE, VENDOR, PROJECT_ID)
VALUES('Home building contract with KB Home', 'P_001', 'Home building in San Francisco' , 1000000,  50000, 60000, 80000, 30, 'KB HOME Builder', 1);

INSERT INTO CONTRACT (NAME, CODE, DESCRIPTION, BUDGET, COMMITTED_COST, FORECAST, PAID, COMPLETED_PERCENTAGE, VENDOR, PROJECT_ID)
VALUES('Home building contract with Material Provider', 'P_001', 'Meterial provider to provide building material' , 100000,  5000, 6000, 100, 100, 'Material Provider', 1);

INSERT INTO CONTRACT (NAME, CODE, DESCRIPTION, BUDGET, COMMITTED_COST, FORECAST, PAID, COMPLETED_PERCENTAGE, VENDOR, PROJECT_ID)
VALUES('Bay bridge contract with bridge builder', 'P_002', 'Bridge should be completed by 2017' , 1000000,  5000, 6000, 100, 100, 'Big Bridge Builder', 2);