DROP TABLE IF EXISTS CONTRACTOR;

CREATE TABLE CONTRACTOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255),
	CODE VARCHAR(12),
	DESCRIPTION VARCHAR(2000),
	BUDGET INT(12),
	COMMITTED_COST INT(12),
	FORECAST INT(12),
	PAID INT(12),
	COMPLETED_PERCENTAGE INT(3),
	VENDOR VARCHAR(64)
);
